2021-05-23 13:29:16,764 INFO    MainThread:35440 [wandb_setup.py:_flush():69] setting env: {}
2021-05-23 13:29:16,764 INFO    MainThread:35440 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-23 13:29:16,764 INFO    MainThread:35440 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210523_132916-29ty10ww\logs\debug.log
2021-05-23 13:29:16,766 INFO    MainThread:35440 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210523_132916-29ty10ww\logs\debug-internal.log
2021-05-23 13:29:16,766 INFO    MainThread:35440 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000029FD2515FA0>
2021-05-23 13:29:16,767 INFO    MainThread:35440 [wandb_init.py:init():369] calling init triggers
2021-05-23 13:29:16,767 INFO    MainThread:35440 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-23 13:29:16,767 INFO    MainThread:35440 [wandb_init.py:init():418] starting backend
2021-05-23 13:29:16,767 INFO    MainThread:35440 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-05-23 13:29:16,770 INFO    MainThread:35440 [backend.py:ensure_launched():132] starting backend process...
2021-05-23 13:29:16,824 INFO    MainThread:35440 [backend.py:ensure_launched():136] started backend process with pid: 14948
2021-05-23 13:29:16,825 INFO    MainThread:35440 [wandb_init.py:init():423] backend started and connected
2021-05-23 13:29:16,877 INFO    MainThread:35440 [wandb_init.py:init():465] updated telemetry
2021-05-23 13:29:16,878 INFO    MainThread:35440 [wandb_init.py:init():484] communicating current version
2021-05-23 13:29:18,187 INFO    MainThread:35440 [wandb_init.py:init():489] got version response 
2021-05-23 13:29:18,187 INFO    MainThread:35440 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-23 13:29:18,547 INFO    MainThread:35440 [wandb_init.py:init():522] starting run threads in backend
2021-05-23 13:29:23,570 INFO    MainThread:35440 [wandb_run.py:_console_start():1565] atexit reg
2021-05-23 13:29:23,571 INFO    MainThread:35440 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-23 13:29:23,571 INFO    MainThread:35440 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-23 13:29:23,571 INFO    MainThread:35440 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-23 13:29:23,571 INFO    MainThread:35440 [wandb_init.py:init():546] run started, returning control to user process
2021-05-23 13:29:23,575 INFO    MainThread:35440 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-23 13:29:23,575 INFO    MainThread:35440 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-23 13:29:23,648 INFO    MainThread:35440 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-23 13:29:23,649 INFO    MainThread:35440 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-23 13:29:23,649 INFO    MainThread:35440 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-23 13:29:23,687 INFO    MainThread:35440 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-23 13:29:24,963 INFO    MainThread:35440 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-23 13:29:24,964 INFO    MainThread:35440 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-23 13:29:24,996 INFO    MainThread:35440 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-23 13:29:24,997 INFO    MainThread:35440 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-23 13:29:24,997 INFO    MainThread:35440 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-23 13:29:25,037 INFO    MainThread:35440 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-23 13:29:25,039 INFO    MainThread:35440 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-23 13:29:25,040 INFO    MainThread:35440 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-23 13:29:25,073 INFO    MainThread:35440 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-23 13:29:25,074 INFO    MainThread:35440 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-23 13:29:25,074 INFO    MainThread:35440 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-23 13:29:25,114 INFO    MainThread:35440 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-23 13:29:34,569 INFO    MainThread:35440 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-23 13:29:34,569 INFO    MainThread:35440 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-23 13:29:34,583 INFO    MainThread:35440 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-23 13:29:34,584 INFO    MainThread:35440 [wandb_run.py:_restore():1507] restore
2021-05-23 13:29:34,686 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 1237
}

2021-05-23 13:29:34,960 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 1237
}

2021-05-23 13:29:35,658 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 17888
}

2021-05-23 13:29:36,018 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12113
  total_bytes: 17890
}

2021-05-23 13:29:36,131 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17890
  total_bytes: 17890
}

2021-05-23 13:29:36,238 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17890
  total_bytes: 17890
}

2021-05-23 13:29:36,346 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17890
  total_bytes: 17890
}

2021-05-23 13:29:36,455 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17890
  total_bytes: 17890
}

2021-05-23 13:29:36,561 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17890
  total_bytes: 17890
}

2021-05-23 13:29:36,671 INFO    MainThread:35440 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17890
  total_bytes: 17890
}

2021-05-23 13:29:37,795 INFO    MainThread:35440 [wandb_run.py:_show_files():1879] logging synced files
