2021-05-22 21:35:01,024 INFO    MainThread:8612 [wandb_setup.py:_flush():69] setting env: {}
2021-05-22 21:35:01,024 INFO    MainThread:8612 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-22 21:35:01,024 INFO    MainThread:8612 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '849f3acb879e58646f94244a57a6323b393471d0'}
2021-05-22 21:35:01,024 INFO    MainThread:8612 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210522_213501-34uyr7fz\logs\debug.log
2021-05-22 21:35:01,024 INFO    MainThread:8612 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210522_213501-34uyr7fz\logs\debug-internal.log
2021-05-22 21:35:01,025 INFO    MainThread:8612 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000210079E5550>
2021-05-22 21:35:01,025 INFO    MainThread:8612 [wandb_init.py:init():369] calling init triggers
2021-05-22 21:35:01,025 INFO    MainThread:8612 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-22 21:35:01,025 INFO    MainThread:8612 [wandb_init.py:init():418] starting backend
2021-05-22 21:35:01,025 INFO    MainThread:8612 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-05-22 21:35:01,029 INFO    MainThread:8612 [backend.py:ensure_launched():132] starting backend process...
2021-05-22 21:35:01,086 INFO    MainThread:8612 [backend.py:ensure_launched():136] started backend process with pid: 35180
2021-05-22 21:35:01,087 INFO    MainThread:8612 [wandb_init.py:init():423] backend started and connected
2021-05-22 21:35:01,163 INFO    MainThread:8612 [wandb_init.py:init():465] updated telemetry
2021-05-22 21:35:01,165 INFO    MainThread:8612 [wandb_init.py:init():484] communicating current version
2021-05-22 21:35:02,476 INFO    MainThread:8612 [wandb_init.py:init():489] got version response 
2021-05-22 21:35:02,476 INFO    MainThread:8612 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-22 21:35:02,870 INFO    MainThread:8612 [wandb_init.py:init():522] starting run threads in backend
2021-05-22 21:35:07,886 INFO    MainThread:8612 [wandb_run.py:_console_start():1565] atexit reg
2021-05-22 21:35:07,887 INFO    MainThread:8612 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-22 21:35:07,887 INFO    MainThread:8612 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-22 21:35:07,887 INFO    MainThread:8612 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-22 21:35:07,887 INFO    MainThread:8612 [wandb_init.py:init():546] run started, returning control to user process
2021-05-22 21:35:07,892 INFO    MainThread:8612 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-22 21:35:07,893 INFO    MainThread:8612 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-22 21:35:07,898 INFO    MainThread:8612 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-22 21:35:07,900 INFO    MainThread:8612 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-22 21:35:07,900 INFO    MainThread:8612 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-22 21:35:07,915 INFO    MainThread:8612 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-22 21:35:07,916 INFO    MainThread:8612 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-22 21:35:07,917 INFO    MainThread:8612 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-22 21:35:07,996 INFO    MainThread:8612 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-22 21:35:07,999 INFO    MainThread:8612 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-22 21:35:07,999 INFO    MainThread:8612 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-22 21:35:17,937 INFO    MainThread:8612 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-22 21:35:17,947 INFO    MainThread:8612 [wandb_setup.py:_flush():69] setting env: {}
2021-05-22 21:35:17,947 INFO    MainThread:8612 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-22 21:35:17,947 INFO    MainThread:8612 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '849f3acb879e58646f94244a57a6323b393471d0'}
2021-05-22 21:35:17,947 INFO    MainThread:8612 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210522_213517-6o7zyke1\logs\debug.log
2021-05-22 21:35:17,948 INFO    MainThread:8612 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210522_213517-6o7zyke1\logs\debug-internal.log
2021-05-22 21:35:17,948 INFO    MainThread:8612 [wandb_init.py:init():369] calling init triggers
2021-05-22 21:35:17,948 INFO    MainThread:8612 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-22 21:35:17,948 INFO    MainThread:8612 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 34uyr7fz
2021-05-22 21:35:17,950 INFO    MainThread:8612 [wandb_run.py:finish():1208] finishing run coinitialized/anomaly/34uyr7fz
